/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:58:40 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Localidades]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Localidades]
(
	[cEstado] varchar(10) NOT NULL,
	[cLocalidad] varchar(10) NOT NULL,
	[cDescripcion] varchar(300) NOT NULL
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Localidades] ADD CONSTRAINT [PK_CAT_Localidades]
		PRIMARY KEY CLUSTERED ([cEstado] ASC,[cLocalidad] ASC)
END
GO