/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:05 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Colonias]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Colonias]
(
	[cColonia] varchar(50) NOT NULL,
	[cCodigoPostal] varchar(50) NOT NULL,
	[cNombreAsentamiento] varchar(300) NOT NULL
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Colonias] ADD CONSTRAINT [PK_CAT_Colonias]
	PRIMARY KEY CLUSTERED ([cColonia] ASC,[cCodigoPostal] ASC)
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_Colonias_CP_Colonia')
	CREATE NONCLUSTERED INDEX IX_Colonias_CP_Colonia ON CAT_Colonias (cCodigoPostal, cColonia)
	INCLUDE (cNombreAsentamiento);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_Colonias_Lookup')
	CREATE NONCLUSTERED INDEX IX_Colonias_Lookup ON CAT_Colonias (cCodigoPostal)
	INCLUDE (cColonia, cNombreAsentamiento);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_Colonias_Order')
	CREATE NONCLUSTERED INDEX IX_Colonias_Order ON CAT_Colonias (cCodigoPostal, cNombreAsentamiento)
	INCLUDE (cColonia);
