/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 29-ago.-2025 09:59:54 a. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Almacenes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Almacenes]
(
	[nAlmacen] int NOT NULL,
	[cDescripcion] varchar(200) NOT NULL,
	[nPlaza] int NOT NULL,
	[nSucursal] int NULL,
	[cEstado] varchar(5) NOT NULL,
	[cLocalidad] varchar(5) NOT NULL,
	[cMunicipio] varchar(5) NOT NULL,
	[cCodigoPostal] varchar(10) NOT NULL,
	[cColonia] varchar(10) NOT NULL,
	[nZona] int NOT NULL,
	[cDomicilio] varchar(300) NOT NULL,
	[cTelefono1] varchar(20) NOT NULL,
	[cTelefono2] varchar(20) NOT NULL,
	[bActivo] bit NOT NULL,
	[cUsuario_Registra] varchar(50) NULL,
	[cMaquina_Registra] varchar(50) NULL,
	[dFecha_Registra] smalldatetime NULL,
	[cUsuario_Modifica] varchar(50) NULL,
	[cMaquina_Modifica] varchar(50) NULL,
	[dFecha_Modifica] varchar(50) NULL,
	[cUsuario_Cancela] varchar(50) NULL,
	[cMaquina_Cancela] varchar(50) NULL,
	[dFecha_Cancela] smalldatetime NULL
)

	/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [dbo].[CAT_Almacenes] ADD CONSTRAINT [PK_CAT_Almacenes]
	PRIMARY KEY CLUSTERED ([nAlmacen] ASC)
END
GO