/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:05 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_ImpuestosArticulos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_ImpuestosArticulos]
(
	[nIDArticulo] int NOT NULL,    -- id
	[nImpuesto] int NOT NULL,    -- id de impuesto relacionado al registro
	[nImporte] decimal(18,4) NULL,    -- cuando el impuesto es IEPS por importe, aqui se indica su valor
	[bDesglosa] bit NOT NULL,    -- cuando el impuesto es ieps, si es requerido se indica si se desglosa o no al venderse
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_ImpuestosArticulos] ADD CONSTRAINT [PK_CAT_ImpuestosArticulos]
	PRIMARY KEY CLUSTERED ([nIDArticulo] ASC,[nImpuesto] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_ImpuestosArticulos_CAT_Articulos' AND xtype = 'F')
	ALTER TABLE [CAT_ImpuestosArticulos] ADD CONSTRAINT [FK_CAT_ImpuestosArticulos_CAT_Articulos]
	FOREIGN KEY ([nIDArticulo]) REFERENCES [CAT_Articulos] ([nIDArticulo]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_ImpuestosArticulos_CAT_Impuestos' AND xtype = 'F')
	ALTER TABLE [CAT_ImpuestosArticulos] ADD CONSTRAINT [FK_CAT_ImpuestosArticulos_CAT_Impuestos]
	FOREIGN KEY ([nImpuesto]) REFERENCES [CAT_Impuestos] ([nImpuesto]) ON DELETE No Action ON UPDATE No Action
GO