/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 11:32:18 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='CAT_HistoricoPrecios' AND xtype = 'U')
BEGIN
CREATE TABLE [CAT_HistoricoPrecios]
(
	[nFolio] int NOT NULL,    -- id
	[nIDArticulo] int NOT NULL,    -- id de catálogo de articulos
	[nIdLista] int NOT NULL,    -- id de catalogo de listas de precio
	[nIdSucursal] int NULL,    -- id de catalogo de sucursal, opcional cuando es precio general
	[nIdMoneda] int NOT NULL,    -- id de catalogo de moneda, default deberia ser id de la moneda base
	[nPrecio] decimal(18,2) NOT NULL,    -- importe del precio de lista
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_HistoricoPrecios] ADD CONSTRAINT [PK_CAT_HistoricoPrecios]
	PRIMARY KEY CLUSTERED ([nFolio] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_HistoricoPrecios_CAT_Articulos' AND xtype = 'F')
	ALTER TABLE [CAT_HistoricoPrecios] ADD CONSTRAINT [FK_CAT_HistoricoPrecios_CAT_Articulos]
	FOREIGN KEY ([nIDArticulo]) REFERENCES [CAT_Articulos] ([nIDArticulo]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_HistoricoPrecios_CAT_ListasPrecio' AND xtype = 'F')
	ALTER TABLE [CAT_HistoricoPrecios] ADD CONSTRAINT [FK_CAT_HistoricoPrecios_CAT_ListasPrecio]
	FOREIGN KEY ([nIdLista]) REFERENCES [CAT_ListasPrecio] ([nIdLista]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_HistoricoPrecios_CAT_Monedas' AND xtype = 'F')
	ALTER TABLE [CAT_HistoricoPrecios] ADD CONSTRAINT [FK_CAT_HistoricoPrecios_CAT_Monedas]
	FOREIGN KEY ([nIdMoneda]) REFERENCES [CAT_Monedas] ([nMoneda]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_HistoricoPrecios_CAT_Sucursales' AND xtype = 'F')
	ALTER TABLE [CAT_HistoricoPrecios] ADD CONSTRAINT [FK_CAT_HistoricoPrecios_CAT_Sucursales]
	FOREIGN KEY ([nIdSucursal]) REFERENCES [dbo].[CAT_Sucursales] ([nSucursal]) ON DELETE No Action ON UPDATE No Action
GO