/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 09-feb.-2025 10:37:16 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='CAT_Parametros' AND xtype = 'U')
BEGIN
CREATE TABLE [dbo].[CAT_Parametros]
(
	[cParametro] varchar(50) NOT NULL,    -- identificador de parámetro
	[cValor] varchar(500) NOT NULL,    -- valor sea numérico o alfanumérico para el parámetro
	[cDescripcion] varchar(200) NOT NULL    -- nota para saber para que sirve el parámetro
)


/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [dbo].[CAT_Parametros] ADD CONSTRAINT [PK_CAT_Parametros]
	PRIMARY KEY CLUSTERED ([cParametro] ASC)
END
GO