/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 16-may.-2024 22:38:32 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SAT_CatRegimenFiscal]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[SAT_CatRegimenFiscal]
(
	[nRegimenFiscal] int NULL,
	[cDescripcion] varchar(300) NULL,
	[bFisica] bit NULL,
	[bMoral] bit NULL
)
END
GO