/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 21-may.-2024 11:06:56 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */
if dbo.FN_Existetabla ('CAT_ClientesRFC')=0
Begin
CREATE TABLE [CAT_ClientesRFC]
(
	[nCliente] int NOT NULL,    -- id de catálogo de cliente
	[nIDRFC] bigint NOT NULL,    -- id de rfc relacionado al cliente
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_ClientesRFC] ADD CONSTRAINT [PK_CAT_ClientesRFC]
	PRIMARY KEY CLUSTERED ([nCliente] ASC,[nIDRFC] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_ClientesRFC_CAT_RFC' AND xtype = 'F')
	ALTER TABLE [CAT_ClientesRFC] ADD CONSTRAINT [FK_CAT_ClientesRFC_CAT_RFC]
	FOREIGN KEY ([nIDRFC]) REFERENCES [dbo].[CAT_RFC] ([nIDRFC]) ON DELETE No Action ON UPDATE No Action
GO