/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 24-may.-2024 09:21:16 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
if dbo.FN_Existetabla ('CAT_CorreosContactoRFC')=0 
Begin
CREATE TABLE [CAT_CorreosContactoRFC]
(
	[nIDRFC] bigint NOT NULL,    -- nombre del registro
	[nFolio] int NOT NULL,    -- id del correo perteneciente al folio de RFC indicado
	[cCorreoElectronico] varchar(100) NOT NULL,   -- correo electrónico de contacto del registro de rfc 
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [CAT_CorreosContactoRFC] ADD CONSTRAINT [PK_CAT_CorreosContactoRFC]
	PRIMARY KEY CLUSTERED ([nFolio] ASC,[nIDRFC] ASC)
END
GO
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_CorreosContactoRFC_CAT_RFC' AND xtype = 'F')
	ALTER TABLE CAT_CorreosContactoRFC ADD CONSTRAINT FK_CAT_CorreosContactoRFC_CAT_RFC
	FOREIGN KEY(nIDRFC) REFERENCES CAT_RFC(nIDRFC)