/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 08-sep.-2023 12:30:16 a. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_EmpleadosBinarios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_EmpleadosBinarios]
(
	[nEmpleado] int NOT NULL,    -- id del empleado del catálogo a los que pertenece los datos
	[cFoto] varchar(max) NULL,    -- imagen del empleado en formato base 64
	[cHuellaDigital] varchar(max) NULL,    -- imagen de la huella digital del empleado en formato base 64
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
 /* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [CAT_EmpleadosBinarios] ADD CONSTRAINT [PK_CAT_EmpleadosBinarios]
	PRIMARY KEY CLUSTERED ([nEmpleado] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_EmpleadosBinarios_CAT_Empleados' AND xtype = 'F')
	ALTER TABLE [CAT_EmpleadosBinarios] ADD CONSTRAINT [FK_CAT_EmpleadosBinarios_CAT_Empleados]
	FOREIGN KEY ([nEmpleado]) REFERENCES [CAT_Empleados] ([nEmpleado]) ON DELETE No Action ON UPDATE No Action
GO