/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 25-sep.-2023 09:44:54 p. m. 			*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_HistoricoEmpleados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_HistoricoEmpleados]
(
	[nEmpleado] int NOT NULL,    -- id de empleado al que pertenece el registro
	[nRenglon] smallint NOT NULL,    -- numero de operacion realizada para la baja o reingreso del empleado
	[nTipoOperacion] tinyint NOT NULL,    -- tipo de operacion  1=Baja 2=Reingreso
	[dFechaOperacion] datetime NOT NULL,    -- fecha del tipo de operación para el empleado indicado
	[cObservaciones] varchar(1000), -- notas relacionadas al tipo de movimiento
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_HistoricoEmpleados] ADD CONSTRAINT [PK_CAT_HistoricoEmpleados]
	PRIMARY KEY CLUSTERED ([nEmpleado] ASC,[Renglon] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_HistoricoEmpleados_CAT_Empleados' AND xtype = 'F')
	ALTER TABLE [CAT_HistoricoEmpleados] ADD CONSTRAINT [FK_CAT_HistoricoEmpleados_CAT_Empleados]
	FOREIGN KEY ([nEmpleado]) REFERENCES [CAT_Empleados] ([nEmpleado]) ON DELETE No Action ON UPDATE No Action
GO

IF NOT EXISTS( SELECT 1 FROM Information_Schema.Columns WHERE TABLE_NAME = 'CAT_HistoricoEmpleados' AND COLUMN_NAME='cObservaciones')
	ALTER TABLE CAT_HistoricoEmpleados ADD cObservaciones varchar(1000)
GO