/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:05 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Regiones]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Regiones]
(
	[nRegion] int NOT NULL,
	[cDescripcion] varchar(50) NULL,
	[bActivo] bit NOT NULL,
	[cMaquina_Registra] varchar(50) NULL,
	[cUsuario_Registra] varchar(50) NULL,
	[dFecha_Registra] smalldatetime NULL,
	[cMaquina_Modifica] varchar(50) NULL,
	[cUsuario_Modifica] varchar(50) NULL,
	[dFecha_Modifica] smalldatetime NULL,
	[cMaquina_Cancela] varchar(50) NULL,
	[cUsuario_Cancela] varchar(50) NULL,
	[dFecha_Cancela] smalldatetime NULL
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Regiones] ADD CONSTRAINT [PK_CAT_Regiones]
	PRIMARY KEY CLUSTERED ([nRegion] ASC)
END
GO