/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 19-feb.-2025 11:42:01 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Cajas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	CREATE TABLE [dbo].[CAT_Cajas]
	(
		[nCaja] int NOT NULL,    -- id llave
		[nSucursal] int NOT NULL,    -- id de sucursal a la que pertence el registro
		[cDescripcion] varchar(100) NOT NULL,    -- descripción de la caja
		[nConsecutivo] smallint NULL,    -- consecutivo de caja por cada registro por sucursal
		[nImpresora] int NOT NULL,    -- id de catálogo de impresora relacionado a una caja
		[bActivo] bit NOT NULL,    -- indicador de si registro está activo
		[cUsuario_Registra] varchar(50) NULL,
		[cMaquina_Registra] varchar(50) NULL,
		[dFecha_Registra] smalldatetime NULL,
		[cUsuario_Modifica] varchar(50) NULL,
		[cMaquina_Modifica] varchar(50) NULL,
		[dFecha_Modifica] varchar(50) NULL,
		[cUsuario_Cancela] varchar(50) NULL,
		[cMaquina_Cancela] varchar(50) NULL,
		[dFecha_Cancela] smalldatetime NULL
	)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Cajas] ADD CONSTRAINT [PK_CAT_Cajas]
	PRIMARY KEY CLUSTERED ([nCaja] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Cajas_CAT_Impresoras' AND xtype = 'F')
	ALTER TABLE [dbo].[CAT_Cajas] ADD CONSTRAINT [FK_CAT_Cajas_CAT_Impresoras]
	FOREIGN KEY ([nImpresora]) REFERENCES [dbo].[CAT_Impresoras] ([nImpresora]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Cajas_CAT_Sucursales' AND xtype = 'F')
	ALTER TABLE [dbo].[CAT_Cajas] ADD CONSTRAINT [FK_CAT_Cajas_CAT_Sucursales]
	FOREIGN KEY ([nSucursal]) REFERENCES [dbo].[CAT_Sucursales] ([nSucursal]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE CAT_Cajas ALTER COLUMN nImpresora int;