/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 29-oct.-2023 10:53:24 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAJ_DetalleMovimientosCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [CAJ_DetalleMovimientosCaja]
(
	[nIDRegistroCaja] bigint NOT NULL,    -- id
	[nRenglon] int NOT NULL,    -- id del renglon relacionado al registro
	[nFormaPago] int NOT NULL,    -- id de catálogo de la forma de pago asociada al detalle del registro de caja
	[nImporte] decimal(18,4) NOT NULL,    -- importe del registro relacionado al detalle
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
	ALTER TABLE [CAJ_DetalleMovimientosCaja] ADD CONSTRAINT [PK_CAJ_DetalleMovimientosCaja]
	PRIMARY KEY CLUSTERED ([nIDRegistroCaja] ASC,[nRenglon] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_DetalleMovimientosCaja_CAJ_MovimientosCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_DetalleMovimientosCaja] ADD CONSTRAINT [FK_CAJ_DetalleMovimientosCaja_CAJ_MovimientosCaja]
	FOREIGN KEY ([nIDRegistroCaja]) REFERENCES [CAJ_MovimientosCaja] ([nIDRegistroCaja]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_DetalleMovimientosCaja_CAT_FormasPago' AND xtype = 'F')
	ALTER TABLE [CAJ_DetalleMovimientosCaja] ADD CONSTRAINT [FK_CAJ_DetalleMovimientosCaja_CAT_FormasPago]
	FOREIGN KEY ([nFormaPago]) REFERENCES [CAT_FormasPago] ([nFormaPago]) ON DELETE No Action ON UPDATE No Action
GO

-- ****************************
IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nOrden')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nOrden bigint
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nCuenta')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nCuenta bigint
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','cReferencia')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD cReferencia varchar(20)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','cReferenciaCuponVale')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD cReferenciaCuponVale varchar(50)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nImporteFacturado')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nImporteFacturado decimal(18,2)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nImportePropina')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nImportePropina decimal(18,2)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nCliente')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nCliente integer
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nEmpleado')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nEmpleado integer
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nPropina')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nPropina decimal(18,2)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nCambio')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nCambio decimal(18,2)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nPagaCon')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nPagaCon decimal(18,2)
GO

IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nImporte_Respaldo')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nImporte_Respaldo numeric(18,2)
GO
IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nPropina_Respaldo')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nPropina_Respaldo numeric(18,2)
GO
IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nCambio_Respaldo')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nCambio_Respaldo numeric(18,2)
GO
IF [dbo].[ValidaCampoTabla_Fn]('CAJ_DetalleMovimientosCaja','nPagaCon_Respaldo')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD nPagaCon_Respaldo numeric(18,2)
GO

IF dbo.fn_ExisteCampo('CAJ_DetalleMovimientosCaja','bCancelado')=0
	ALTER TABLE CAJ_DetalleMovimientosCaja ADD bCancelado bit
GO