/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 19-feb.-2025 11:59:32 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[VTA_MovimientosVentaDetalle]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [VTA_MovimientosVentaDetalle]
(
	[nVenta] bigint NOT NULL,    -- id de cabecero de venta a la que pertenece el registro
	[nRenglon] smallint NOT NULL,    -- parte de la llave para identificar la cantidad de registros por venta
	[nIDArticulo] int NOT NULL,    -- id de catálogo de artículo del que se registra la venta
	[nCantidad] decimal(18,4) NOT NULL,    -- cantidad del artículo en el registro
	[nCantidadDevuelta] decimal(18,4) NOT NULL,    -- cantidad devuelta del artículo en el registro
	[nPrecioUnitario] decimal(18,2) NOT NULL,    -- precio unitario con impuestos del artículo
	[nPrecioOriginal] decimal(18,2) NULL,    -- precio original del artículo para cuando se hace algun ajuste de precio para la venta
	[nSubtotal] decimal(18,4) NOT NULL,    -- importe subtotal de la partida
	[nImpuestoIVA] decimal(18,4) NOT NULL,    -- importe de impuesto de tipo iva
	[nIDImpuestoIVA] int NOT NULL,    -- id de catálogo de impuesto para el iva
	[nPorcentajeImpuestoIVA] tinyint NOT NULL,    -- valor del porcentaje del impuesto de iva aplicado para el artículo
	[nImpuestoIEPS] decimal(18,4) NULL,    -- importe de impuesto de tipo IEPS
	[nIDImpuestoIEPS] int NULL,    -- id de catálogo de impuesto para el IEPS
	[nPorcentajeImpuestoIEPS] tinyint NULL,    -- valor del porcentaje del impuesto de iva aplicado para el artículo (si el ieps aplica se desglose y este haya sido por porcentaje)
	[nImporteDescuento] decimal(18,2) NULL,    -- importe de descuento en la venta basado de manera directa o el resultado de basarlo en un porcentaje
	[nPorcentajeDescuento] decimal(18,2) NULL,    -- campo para cuando se realice descuento basado en un porcentaje
	[nTotal] decimal(18,2) NOT NULL,    -- importe total de la venta
	[cComentarios] varchar(2000) NULL,    -- notas a nivel detalle de venta
	[nCostoUnitario] decimal(18,4) NULL,    -- campo para cuando se lleva control de inventarios marcar el costo que se tenia del artículo a nivel sucursal en el momento de la venta
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)


/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [VTA_MovimientosVentaDetalle] ADD CONSTRAINT [PK_VTA_MovimientosVentaDetalle]
	PRIMARY KEY CLUSTERED ([nVenta] ASC,[nRenglon] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_MovimientosVentaDetalle_CAT_Articulos' AND xtype = 'F')
	ALTER TABLE [VTA_MovimientosVentaDetalle] ADD CONSTRAINT [FK_VTA_MovimientosVentaDetalle_CAT_Articulos]
	FOREIGN KEY ([nIDArticulo]) REFERENCES [CAT_Articulos] ([nIDArticulo]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_MovimientosVentaDetalle_VTA_MovimientosVenta' AND xtype = 'F')
	ALTER TABLE [VTA_MovimientosVentaDetalle] ADD CONSTRAINT [FK_VTA_MovimientosVentaDetalle_VTA_MovimientosVenta]
	FOREIGN KEY ([nVenta]) REFERENCES [VTA_MovimientosVenta] ([nVenta]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_MovimientosVentaDetalleIEPS_CAT_Impuestos' AND xtype = 'F')
	ALTER TABLE [VTA_MovimientosVentaDetalle] ADD CONSTRAINT [FK_VTA_MovimientosVentaDetalleIEPS_CAT_Impuestos]
	FOREIGN KEY ([nIDImpuestoIEPS]) REFERENCES [CAT_Impuestos] ([nImpuesto]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_MovimientosVentaDetalleIVA_CAT_Impuestos' AND xtype = 'F')
	ALTER TABLE [VTA_MovimientosVentaDetalle] ADD CONSTRAINT [FK_VTA_MovimientosVentaDetalleIVA_CAT_Impuestos]
	FOREIGN KEY ([nIDImpuestoIVA]) REFERENCES [CAT_Impuestos] ([nImpuesto]) ON DELETE No Action ON UPDATE No Action
GO