/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 17-sep.-2023 09:17:59 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_TiposMovimientosInventario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_TiposMovimientosInventario]
(
	[nTipoMovimiento] int NOT NULL,    -- id
	[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
	[nEfecto] smallint NOT NULL,    -- tipo de efecto que tendrá el tipo de movimiento en la existencia al usarlo en un movimiento de inventario
	[bRestringido] bit NOT NULL,    -- campo para saber si el registro será de uso particular en pantallas específicas o procesos
	[bEsCancelacion] bit NOT NULL,    -- campo para saber si es un tipo de movimiento restringido de tipo cancelación para un contramovimiento
	[nContramovimiento] int NULL,    -- tipo de movimiento de tipo cancelación que sirve de efecto contrario al del registro  ejemplo una entrada tendria de contramovimiento una salida
	[nTipoInvolucrado] tinyint NOT NULL,    -- campo para saber el tipo de involucrado relacionado al registro  valores  1=Almacen 2=Empleado 3=Involucrado 4=Proveedor 5=Cliente
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_TiposMovimientosInventario] ADD CONSTRAINT [PK_CAT_TiposMovimientosInventario]
	PRIMARY KEY CLUSTERED ([nTipoMovimiento] ASC)
END
GO

/* Create Foreign Key Constraints */

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_TiposMovimientosInventario_ContraMov' AND xtype = 'F')
	ALTER TABLE [CAT_TiposMovimientosInventario] ADD CONSTRAINT [FK_CAT_TiposMovimientosInventario_ContraMov]
	FOREIGN KEY ([nContramovimiento]) REFERENCES [CAT_TiposMovimientosInventario] ([nTipoMovimiento]) ON DELETE No Action ON UPDATE No Action
GO