/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 20-mar.-2025 12:23:42 a. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[IVT_Existencias]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [IVT_Existencias]
(
	[nAlmacen] int NOT NULL,    -- id de catálogo de almacenes al que pertenece el registro
	[nIDArticulo] int NOT NULL,    -- id de catálogo de artículo al que pertenece el registro
	[nExistencia] decimal(18,4) NOT NULL,    -- valor de la existencia del artículo en el almacén indicado
	[nValorInventario] decimal(18,4) NOT NULL,    -- valor de inventario del artículo en el almacén de inventario, su importe entre la existencia daría el dato de costo promedio
	[nUltimoCosto] decimal(18,4) NOT NULL,    -- valor del último costo aplicado para el artículo en el almacén indicado
	[nApartado] decimal(18,4) NOT NULL,    -- valor de cantidad apartada del artículo en el almacén indicado
	[nBackOrder] decimal(18,4) NOT NULL,    -- valor de cantidad requerido que no se pudo procesar y está en espera del artículo en el almacén indicado
	[nFechaUltimoMovimientoEntrada] int NULL,    -- valor en formato número de la ultima vez que se hizo una entrada en el almacén del artículo indicado
	[nFechaUltimoMovimientoSalida] int NULL,    -- valor en formato número de la ultima vez que se hizo una salida en el almacén del artículo indicado
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)


/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [IVT_Existencias] ADD CONSTRAINT [PK_IVT_Existencias]
	PRIMARY KEY CLUSTERED ([nAlmacen] ASC,[nIDArticulo] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_Existencias_CAT_Almacenes' AND xtype = 'F')
	ALTER TABLE [IVT_Existencias] ADD CONSTRAINT [FK_IVT_Existencias_CAT_Almacenes]
	FOREIGN KEY ([nAlmacen]) REFERENCES [dbo].[CAT_Almacenes] ([nAlmacen]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_Existencias_CAT_Articulos' AND xtype = 'F')
	ALTER TABLE [IVT_Existencias] ADD CONSTRAINT [FK_IVT_Existencias_CAT_Articulos]
	FOREIGN KEY ([nIDArticulo]) REFERENCES [CAT_Articulos] ([nIDArticulo]) ON DELETE No Action ON UPDATE No Action
GO