/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:06 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Unidades]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_Unidades]
(
	[nUnidad] int NOT NULL,    -- id
	[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
	[cAbreviatura] varchar(5) NULL,    -- abreviatura para la unidad de medida
	[nTipoUnidad] tinyint NOT NULL,    -- tipo de unidad de medida  1=Peso 2=Liquido 3=Pieza
	[cClaveSAT] varchar(10) NOT NULL,    -- clave SAT para la unidad de medida
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_Unidades] ADD CONSTRAINT [PK_CAT_Unidades]
		PRIMARY KEY CLUSTERED ([nUnidad] ASC)
END
GO