/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 21-may.-2024 11:35:09 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */
if dbo.FN_Existetabla ('CAT_Impuestos')=0 
Begin
CREATE TABLE [CAT_Impuestos]
(
	[nImpuesto] int NOT NULL,    -- id
	[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
	[nPorcentaje] decimal(18,2) NOT NULL,    -- valor de porcentaje de impuesto
	[nTipo] tinyint NOT NULL,    -- tipo de impuesto  1=IVA 2=IEPS
	[bImpuestoImporte] bit NOT NULL,    -- si tipo de impuesto es IEPS, este campo indicaría si el impuesto es un valor en vez de calcularlo con porcentaje, este variaría por artículo al que se relaciona
	[bExcento] bit NOT NULL,    -- campo para saber si el impuesto es de tipo excento
	[c_Impuesto] varchar(8) NOT NULL,    -- clave de impuesto SAT relacionado al registro
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL,    -- fecha en que se hace la ultima inactivación del registro
	[cTipoFactor] varchar(10) NULL,    -- descripcion del tipo de factor SAT para el impuesto
	[nTasaOCuota] decimal(18,6) NULL    -- porcentaje de impuesto formato decimal  ejemplo 16%=  0.160000
)

/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [CAT_Impuestos] ADD CONSTRAINT [PK_CAT_Impuestos]
	PRIMARY KEY CLUSTERED ([nImpuesto] ASC)
END
GO