/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 14-ago.-2023 09:52:25 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_OperacionesRestringidas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_OperacionesRestringidas]
(
	[nOperacionRestringida] int NOT NULL,    -- id
	[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
	[cObservaciones] varchar(2000) NULL,    -- campo adicional para describir más ampliamente a la operación restringida
	[nModulo] int NULL,    -- campo opcional, id del módulo al que se pueda asignar a una operación restringida
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
	ALTER TABLE [CAT_OperacionesRestringidas] ADD CONSTRAINT [PK_CAT_OperacionesRestringidas]
	PRIMARY KEY CLUSTERED ([nOperacionRestringida] ASC)
END
GO


IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_PermisosOperacionesRestringidas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_PermisosOperacionesRestringidas]
(
	[nOperacionRestringida] int NOT NULL,    -- id de la operación restringida a la que se le asignarán permisos
	[nUsuario] int NOT NULL,    -- id de usuario al que se le asigna permiso a la operación restringida
	[cToken] varchar(100) NOT NULL,    -- cadena encriptada para validar que si se está haciendo una relación de permiso válido para un usuario a una operación restringida
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
	ALTER TABLE [CAT_PermisosOperacionesRestringidas] ADD CONSTRAINT [PK_CAT_PermisosOperacionesRestringidas]
	PRIMARY KEY CLUSTERED ([nOperacionRestringida] ASC,[nUsuario] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_OperacionesRestringidas_CAT_ModulosMenu' AND xtype = 'F')
	ALTER TABLE [CAT_OperacionesRestringidas] ADD CONSTRAINT [FK_CAT_OperacionesRestringidas_CAT_ModulosMenu]
	FOREIGN KEY ([nModulo]) REFERENCES [CAT_ModulosMenu] ([nModulo]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_PermisosOperacionesRestringidas_CAT_OperacionesRestringidas' AND xtype = 'F')
	ALTER TABLE [CAT_PermisosOperacionesRestringidas] ADD CONSTRAINT [FK_CAT_PermisosOperacionesRestringidas_CAT_OperacionesRestringidas]
	FOREIGN KEY ([nOperacionRestringida]) REFERENCES [CAT_OperacionesRestringidas] ([nOperacionRestringida]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_PermisosOperacionesRestringidas_CAT_Usuarios' AND xtype = 'F')
	ALTER TABLE [CAT_PermisosOperacionesRestringidas] ADD CONSTRAINT [FK_CAT_PermisosOperacionesRestringidas_CAT_Usuarios]
	FOREIGN KEY ([nUsuario]) REFERENCES [CAT_Usuarios] ([nFolio]) ON DELETE No Action ON UPDATE No Action
GO