/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 06-ago.-2023 11:11:31 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_PerfilesUsuarios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_PerfilesUsuarios]
(
	[nUsuario] int NOT NULL,    -- id de usuario al que pertenece el registro
	[nPerfil] int NOT NULL,    -- id de perfil asignado al usuario
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	ALTER TABLE [CAT_PerfilesUsuarios] ADD CONSTRAINT [PK_CAT_PerfilesUsuarios]
	PRIMARY KEY CLUSTERED ([nUsuario] ASC,[nPerfil] ASC)
END
GO

/* Create Foreign Key Constraints */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CAT_PerfilesUsuarios_CAT_Perfiles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
	ALTER TABLE [CAT_PerfilesUsuarios] ADD CONSTRAINT [FK_CAT_PerfilesUsuarios_CAT_Perfiles]
	FOREIGN KEY ([nPerfil]) REFERENCES [CAT_Perfiles] ([nPerfil]) ON DELETE No Action ON UPDATE No Action
GO

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CAT_PerfilesUsuarios_CAT_Usuarios]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
	ALTER TABLE [CAT_PerfilesUsuarios] ADD CONSTRAINT [FK_CAT_PerfilesUsuarios_CAT_Usuarios]
	FOREIGN KEY ([nUsuario]) REFERENCES [CAT_Usuarios] ([nFolio]) ON DELETE No Action ON UPDATE No Action
GO