IF EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_OpcionesMenu_CAT_OpcionesMenuPadre' AND xtype = 'F')
	ALTER TABLE CAT_OpcionesMenu DROP CONSTRAINT FK_CAT_OpcionesMenu_CAT_OpcionesMenuPadre
GO

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 01-ago.-2023 11:24:17 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */


/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_AgrupadoresMenu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
	CREATE TABLE [CAT_AgrupadoresMenu]
	(
		[nAgrupador] int NOT NULL,    -- id
		[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
		[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
		[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
		[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
		[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
		[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
		[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
		[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
		[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
		[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
		[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
	)

	ALTER TABLE [CAT_AgrupadoresMenu] ADD CONSTRAINT [PK_CAT_AgrupadoresMenu]
	PRIMARY KEY CLUSTERED ([nAgrupador] ASC)
END
GO

/* Create Primary Keys, Indexes, Uniques, Checks */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_OpcionesMenu_CAT_AgrupadoresMenu' AND xtype = 'F')
	ALTER TABLE CAT_OpcionesMenu ADD CONSTRAINT FK_CAT_OpcionesMenu_CAT_AgrupadoresMenu
	FOREIGN KEY (nOpcionAgrupador) REFERENCES CAT_AgrupadoresMenu(nAgrupador)
GO
