/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 31-jul.-2023 09:46:55 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_ModulosMenu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
--DROP TABLE [CAT_ModulosMenu]
BEGIN
	CREATE TABLE [CAT_ModulosMenu]
	(
		[nModulo] int NOT NULL,    -- id
		[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
		[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
		[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
		[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
		[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
		[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
		[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
		[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
		[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
		[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
		[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
	)
	ALTER TABLE [CAT_ModulosMenu] ADD CONSTRAINT [PK_CAT_ModulosMenu]
	PRIMARY KEY CLUSTERED ([nModulo] ASC)
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_OpcionesMenu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
--DROP TABLE [CAT_OpcionesMenu]
BEGIN
	CREATE TABLE [CAT_OpcionesMenu]
	(
		[nOpcion] int NOT NULL,    -- id
		[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
		[nModulo] int NOT NULL,    -- id del módulo al que pertene la opción
		[cFormulario] varchar(50) NULL,    -- nombre del formulario con el que se instanciará la opción
		[cComponenteInstancia] varchar(50) NULL,    -- nombre del componente dll o ruta web de donde se instanciaría a la opción
		[nOpcionAgrupador] int NULL,    -- id de opción que pudiera servir de agrupador secundario
		[nOrden] smallint NULL,    -- valor opcional, indicado por módulo para en caso que se desee establecer un orden en el menú
		[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
		[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
		[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
		[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
		[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
		[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
		[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
		[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
		[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
		[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
	)
	ALTER TABLE [CAT_OpcionesMenu] ADD CONSTRAINT [PK_CAT_OpcionesMenu]
	PRIMARY KEY CLUSTERED ([nOpcion] ASC)
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_PermisosMenu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
--DROP TABLE [CAT_PermisosMenu]
BEGIN
	CREATE TABLE [CAT_PermisosMenu]
	(
		[nPermiso] int NOT NULL,    -- llave
		[nOpcion] int NOT NULL,    -- id de la opción de menú
		[nPerfil] int NULL,    -- id del perfil del permiso al que puede pertenecer la opción
		[nUsuario] int NULL,    -- id de usuario al que se asigna directamente la opción del sistema
		[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
		[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
		[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
		[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
		[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
		[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
		[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
		[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
		[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
		[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
	)
	ALTER TABLE [CAT_PermisosMenu] ADD CONSTRAINT [PK_CAT_PermisosMenu]
	PRIMARY KEY CLUSTERED ([nPermiso] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_OpcionesMenu_CAT_ModulosMenu' AND xtype = 'F')
	ALTER TABLE [CAT_OpcionesMenu] ADD CONSTRAINT [FK_CAT_OpcionesMenu_CAT_ModulosMenu]
	FOREIGN KEY ([nModulo]) REFERENCES [CAT_ModulosMenu] ([nModulo]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_OpcionesMenu_CAT_OpcionesMenuPadre' AND xtype = 'F')
	ALTER TABLE [CAT_OpcionesMenu] ADD CONSTRAINT [FK_CAT_OpcionesMenu_CAT_OpcionesMenuPadre]
	FOREIGN KEY ([nOpcionAgrupador]) REFERENCES [CAT_OpcionesMenu] ([nOpcion]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_PermisosMenu_CAT_OpcionesMenu' AND xtype = 'F')
	ALTER TABLE [CAT_PermisosMenu] ADD CONSTRAINT [FK_CAT_PermisosMenu_CAT_OpcionesMenu]
	FOREIGN KEY ([nOpcion]) REFERENCES [CAT_OpcionesMenu] ([nOpcion]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_PermisosMenu_CAT_Perfiles' AND xtype = 'F')
	ALTER TABLE [CAT_PermisosMenu] ADD CONSTRAINT [FK_CAT_PermisosMenu_CAT_Perfiles]
	FOREIGN KEY ([nPerfil]) REFERENCES [CAT_Perfiles] ([nPerfil]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_PermisosMenu_CAT_Usuarios' AND xtype = 'F')
	ALTER TABLE [CAT_PermisosMenu] ADD CONSTRAINT [FK_CAT_PermisosMenu_CAT_Usuarios]
	FOREIGN KEY ([nUsuario]) REFERENCES [CAT_Usuarios] ([nFolio]) ON DELETE No Action ON UPDATE No Action
GO
