IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Usuarios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
	IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name = 'PK_CAT_Usuarios' AND xtype = 'PK')
		ALTER TABLE [CAT_Usuarios] ADD CONSTRAINT [PK_CAT_Perfiles]
		PRIMARY KEY CLUSTERED ([nPerfil] ASC)
GO
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 28-jul.-2023 11:23:11 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Perfiles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
/* Create Tables */

CREATE TABLE [CAT_Perfiles]
(
	[nPerfil] int NOT NULL,    -- id
	[cDescripcion] varchar(200) NOT NULL,    -- nombre del registro
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_Perfiles] ADD CONSTRAINT [PK_CAT_Perfiles]
	PRIMARY KEY CLUSTERED ([nPerfil] ASC)
END
GO

