/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 19-feb.-2025 11:59:33 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[VTA_ValesCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [VTA_ValesCaja]
(
	[nValeCaja] bigint NOT NULL,    -- id del vale de caja
	[nSucursal] int NOT NULL,    -- id de sucursal donde se registro el vale
	[nVentaOrigen] bigint NOT NULL,    -- id del registro de venta que originó el vale de caja
	[dFechaExpiracion] datetime NULL,    -- en caso que los vales de caja tengan una fecha límite de uso en este campo se guardaría la fecha hasta el cual el vale tiene vigencia
	[nImporte] decimal(18,2) NOT NULL,    -- importe del vale de caja
	[nSaldo] decimal(18,2) NOT NULL,    -- saldo que le queda por aplicar del vale de caja
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [VTA_ValesCaja] ADD CONSTRAINT [PK_VTA_ValesCaja]
	PRIMARY KEY CLUSTERED ([nValeCaja] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_ValesCaja_CAT_Sucursales' AND xtype = 'F')
	ALTER TABLE [VTA_ValesCaja] ADD CONSTRAINT [FK_VTA_ValesCaja_CAT_Sucursales]
	FOREIGN KEY ([nSucursal]) REFERENCES [dbo].[CAT_Sucursales] ([nSucursal]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_ValesCaja_VTA_MovimientosVenta' AND xtype = 'F')
	ALTER TABLE [VTA_ValesCaja] ADD CONSTRAINT [FK_VTA_ValesCaja_VTA_MovimientosVenta]
	FOREIGN KEY ([nVentaOrigen]) REFERENCES [VTA_MovimientosVenta] ([nVenta]) ON DELETE No Action ON UPDATE No Action
GO