/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 19-feb.-2025 11:59:31 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[VTA_BitacoraValesCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [VTA_BitacoraValesCaja]
(
	[nBitacora] bigint NOT NULL,    -- id
	[nValeCaja] bigint NOT NULL,    -- id del vale de caja al que pertenece el registro
	[nVenta] bigint NOT NULL,    -- id de registro de venta en el que se aplica el vale de caja
	[nImporte] decimal(18,2) NOT NULL,    -- importe aplicado del vale de caja
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)


/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [VTA_BitacoraValesCaja] ADD CONSTRAINT [PK_VTA_BitacoraValesCaja]
	PRIMARY KEY CLUSTERED ([nBitacora] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_BitacoraValesCaja_VTA_MovimientosVenta' AND xtype = 'F')
	ALTER TABLE [VTA_BitacoraValesCaja] ADD CONSTRAINT [FK_VTA_BitacoraValesCaja_VTA_MovimientosVenta]
	FOREIGN KEY ([nVenta]) REFERENCES [VTA_MovimientosVenta] ([nVenta]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_VTA_BitacoraValesCaja_VTA_ValesCaja' AND xtype = 'F')
	ALTER TABLE [VTA_BitacoraValesCaja] ADD CONSTRAINT [FK_VTA_BitacoraValesCaja_VTA_ValesCaja]
	FOREIGN KEY ([nValeCaja]) REFERENCES [VTA_ValesCaja] ([nValeCaja]) ON DELETE No Action ON UPDATE No Action
GO