/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:05 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Empresas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Empresas]
(
	[nEmpresa] int NOT NULL,
	[cDescripcion] varchar(100) NOT NULL,
	[nGrupoEmpresarial] int NOT NULL,
	[bActivo] bit NOT NULL,
	[cUsuario_Registra] varchar(50) NULL,
	[cMaquina_Registra] varchar(50) NULL,
	[dFecha_Registra] smalldatetime NULL,
	[cUsuario_Modifica] varchar(50) NULL,
	[cMaquina_Modifica] varchar(50) NULL,
	[dFecha_Modifica] varchar(50) NULL,
	[cUsuario_Cancela] varchar(50) NULL,
	[cMaquina_Cancela] varchar(50) NULL,
	[dFecha_Cancela] smalldatetime NULL,
	[cLogo] varchar(max) NULL    -- imagen en base 64 del logo de la empresa
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Empresas] ADD CONSTRAINT [PK_CAT_Empresas]
	PRIMARY KEY CLUSTERED ([nEmpresa] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Empresas_CAT_GrupoEmpresarial' AND xtype = 'F')
	ALTER TABLE [dbo].[CAT_Empresas] ADD CONSTRAINT [FK_CAT_Empresas_CAT_GrupoEmpresarial]
	FOREIGN KEY ([nGrupoEmpresarial]) REFERENCES [dbo].[CAT_GrupoEmpresarial] ([nGrupoEmpresarial]) ON DELETE No Action ON UPDATE No Action
GO