/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:58:39 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Estados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Estados]
(
	[cEstado] varchar(10) NOT NULL,
	[cPais] varchar(10) NOT NULL,
	[cNombreEstado] varchar(100) NOT NULL
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Estados] ADD CONSTRAINT [PK_CAT_Estados_1]
	PRIMARY KEY CLUSTERED ([cEstado] ASC)
END
GO