/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:58:40 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Municipios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_Municipios]
(
	[cMunicipio] varchar(50) NOT NULL,
	[cEstado] varchar(10) NOT NULL,
	[cNombreMunicipio] varchar(300) NULL
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_Municipios] ADD CONSTRAINT [PK_CAT_Municipios]
	PRIMARY KEY CLUSTERED ([cMunicipio] ASC,[cEstado] ASC)
END
GO