/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:05 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_CodigosPostales]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_CodigosPostales]
(
	[cCodigoPostal] varchar(20) NOT NULL,
	[cEstado] varchar(50) NOT NULL,
	[cMunicipio] varchar(50) NOT NULL,
	[cLocalidad] varchar(50) NOT NULL
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_CodigosPostales] ADD CONSTRAINT [PK_CAT_CodigosPostales]
	PRIMARY KEY CLUSTERED ([cCodigoPostal] ASC,[cEstado] ASC,[cMunicipio] ASC,[cLocalidad] ASC)
END
GO