/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 15-ene.-2024 09:36:10 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
if dbo.FN_Existetabla ('CAT_Parametros')=0 
BEGIN
CREATE TABLE [dbo].[CAT_Parametros]
(
	[cParametro] varchar(50) NOT NULL,    -- identificador de parámetro
	[cValor] varchar(500) NOT NULL,    -- valor sea numérico o alfanumérico para el parámetro
	[cDescripcion] varchar(200) NOT NULL    -- nota para saber para que sirve el parámetro
)
END
GO

/* Create Primary Keys, Indexes, Uniques, Checks */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name = 'PK_CAT_Parametros' AND xtype = 'PK')
	ALTER TABLE [dbo].[CAT_Parametros] ADD CONSTRAINT [PK_CAT_Parametros]
	PRIMARY KEY CLUSTERED ([cParametro] ASC)
GO