/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 16-may.-2024 22:38:30 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

/* Create Tables */
if dbo.FN_Existetabla ('CAT_RFC')=0
Begin
CREATE TABLE [dbo].[CAT_RFC]
(
	[nIDRFC] bigint NOT NULL,
	[cRazonSocial] varchar(500) NOT NULL,
	[cRFC] varchar(50) NOT NULL,
	[cCP] varchar(10) NOT NULL,
	[cDomicilio] varchar(500) NULL,
	[cUso_CFDI] varchar(5) NOT NULL,
	[cRegimenFiscal] varchar(5) NOT NULL,
	[bActivo] bit NULL DEFAULT 1
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_RFC] ADD CONSTRAINT [PK_CAT_RFC]
	PRIMARY KEY CLUSTERED ([nIDRFC] ASC)
END
GO

if dbo.fn_ExisteCampo ('CAT_RFC', 'cRazonSocial')=1 
Begin
	Alter table CAT_RFC alter column cRazonSocial Varchar(500);
End 