/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 09-feb.-2025 11:40:52 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
if dbo.FN_Existetabla ('CAT_ClientesContactos')=0
Begin
CREATE TABLE [CAT_ClientesContactos]
(
	[nCliente] bigint NOT NULL,    -- id
	[nContacto] smallint NOT NULL,    -- numero consecutivo de contacto para el cliente indicado
	[cNombre] varchar(500) NOT NULL,    -- nombre del contacto
	[cPuesto] varchar(200) NOT NULL,    -- descripcion del puesto del contacto
	[cTelefono] varchar(30) NULL,    -- número de teléfono fijo del contacto
	[cCelular] varchar(30) NOT NULL,    -- número de teléfono celular del contacto
	[cCorreoElectronico] varchar(100) NOT NULL,    -- correo electronico del contacto
	[nTipoContacto] tinyint NOT NULL,    -- clasificacion de tipo de contacto  sus valores son del cat catalogos "CAT_TipoContactoCliente"
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_ClientesContactos] ADD CONSTRAINT [PK_CAT_ClientesContactos]
	PRIMARY KEY CLUSTERED ([nCliente] ASC,[nContacto] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_ClientesContactos_CAT_Clientes' AND xtype = 'F')
	ALTER TABLE [CAT_ClientesContactos] ADD CONSTRAINT [FK_CAT_ClientesContactos_CAT_Clientes]
	FOREIGN KEY ([nCliente]) REFERENCES [dbo].[CAT_Clientes] ([nCliente]) ON DELETE No Action ON UPDATE No Action
GO