/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 07-sep.-2023 11:10:50 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Empleados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_Empleados]
(
	[nEmpleado] int NOT NULL,    -- id
	[cNombre] varchar(50) NOT NULL,    -- nombre de pila del empleado
	[cApellidoPaterno] varchar(50) NOT NULL,    -- apellido paterno del empleado
	[cApellidoMaterno] varchar(50) NULL,    -- apellido materno del empleado
	[nEmpresa] int NULL,    -- id de catálogo de empresa a la que pertenece el empleado
	[dFechaNacimiento] datetime NOT NULL,    -- fecha de nacimiento del empleado
	[dFechaIngreso] datetime NOT NULL,    -- fecha de ingreso del empleado a la empresa
	[dFechaBaja] datetime NULL,    -- fecha de baja del empleado
	[cRFC] varchar(20) NULL,    -- rfc del empleado
	[cCURP] varchar(50) NULL,    -- dato de CURP del empleado
	[cColonia] varchar(50) NOT NULL,    -- id de catálogo de la colonia del domicilio del empleado
	[cCodigoPostal] varchar(50) NOT NULL,    -- código postal de la dirección del empleado
	[cDomicilio] varchar(50) NOT NULL,    -- dato del domicilio del empleado
	[cReferencia] varchar(100) NULL,    -- referencia del domicilio del empleado
	[nSucursal] int NULL,    -- id de catálogo de la sucursal a la que pertenece el empleado
	[nPuesto] int NULL,    -- id de catálogo del puesto del empleado
	[nDepartamento] int NULL,    -- id de catálogo del departamento al que pertenece el empleado
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificaciób del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[cRegistro_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_Empleados] ADD CONSTRAINT [PK_CAT_Empleados]
	PRIMARY KEY CLUSTERED ([nEmpleado] ASC)
END
GO

/* Create Foreign Key Constraints */

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Empleados_CAT_Colonias' AND xtype = 'F')
	ALTER TABLE [CAT_Empleados] ADD CONSTRAINT [FK_CAT_Empleados_CAT_Colonias]
	FOREIGN KEY ([cColonia],[cCodigoPostal]) REFERENCES [dbo].[CAT_Colonias] ([cColonia],[cCodigoPostal]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Empleados_CAT_Empresas' AND xtype = 'F')
	ALTER TABLE [CAT_Empleados] ADD CONSTRAINT [FK_CAT_Empleados_CAT_Empresas]
	FOREIGN KEY ([nEmpresa]) REFERENCES [dbo].[CAT_Empresas] ([nEmpresa]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Empleados_CAT_Sucursales' AND xtype = 'F')
	ALTER TABLE [CAT_Empleados] ADD CONSTRAINT [FK_CAT_Empleados_CAT_Sucursales]
	FOREIGN KEY ([nSucursal]) REFERENCES [dbo].[CAT_Sucursales] ([nSucursal]) ON DELETE No Action ON UPDATE No Action
GO