/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 29-oct.-2023 10:53:24 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAJ_MovimientosCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAJ_MovimientosCaja]
(
	[nIDRegistroCaja] bigint NOT NULL,    -- id
	[nTipoRegistroCaja] int NOT NULL,    -- id de catálgo de tipo de registro de caja
	[nSucursal] int NOT NULL,    -- id de catálogo de sucursal a la que pertenece el registro
	[nIDApertura] bigint NOT NULL,    -- id de apertura de caja al que pertenece el registro
	[nConceptoCaja] int NULL,    -- campo opcional, dependiendo del tipo de registro de caja este dato tendria valor del catálogo correspondiente
	[nEmpleadoInvolucrado] int NULL,    -- opcional, dependiendo del tipo de movimiento de caja este campo sería el id del empleado involucrado en el registro
	[nImporte] decimal(18,4) NOT NULL,    -- importe del movimiento de caja
	[nEfecto] smallint NOT NULL,    -- efecto del movimiento para sumarizar a la caja  valores  1 = Ingreso -1 = Egreso
	[dFecha] datetime NOT NULL,
	[nFecha] int,
	[cObservaciones] varchar(5000),
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [PK_CAJ_MovimientosCaja]
	PRIMARY KEY CLUSTERED ([nIDRegistroCaja] ASC)
END
GO


/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_MovimientosCaja_CAJ_RegistrosAperturaCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [FK_CAJ_MovimientosCaja_CAJ_RegistrosAperturaCaja]
	FOREIGN KEY ([nIDApertura]) REFERENCES [CAJ_RegistrosAperturaCaja] ([nIDApertura]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_MovimientosCaja_CAT_ConceptosCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [FK_CAJ_MovimientosCaja_CAT_ConceptosCaja]
	FOREIGN KEY ([nConceptoCaja]) REFERENCES [CAT_ConceptosCaja] ([nConceptoCaja]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_MovimientosCaja_CAT_Empleados' AND xtype = 'F')	
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [FK_CAJ_MovimientosCaja_CAT_Empleados]
	FOREIGN KEY ([nEmpleadoInvolucrado]) REFERENCES [CAT_Empleados] ([nEmpleado]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_MovimientosCaja_CAT_Sucursales' AND xtype = 'F')
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [FK_CAJ_MovimientosCaja_CAT_Sucursales]
	FOREIGN KEY ([nSucursal]) REFERENCES [dbo].[CAT_Sucursales] ([nSucursal]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_MovimientosCaja_CAT_TiposRegistroCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [FK_CAJ_MovimientosCaja_CAT_TiposRegistroCaja]
	FOREIGN KEY ([nTipoRegistroCaja]) REFERENCES [CAT_TiposRegistroCaja] ([nTipoRegistroCaja]) ON DELETE No Action ON UPDATE No Action
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','nConsecutivo')=0
	ALTER TABLE CAJ_MovimientosCaja ADD nConsecutivo int
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','cUsuarioAutoriza_Registro')=0
	ALTER TABLE CAJ_MovimientosCaja ADD cUsuarioAutoriza_Registro varchar(100)
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','cUsuarioAutoriza_Modificacion')=0
	ALTER TABLE CAJ_MovimientosCaja ADD cUsuarioAutoriza_Modificacion varchar(100)
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','cUsuarioAutoriza_Cancelacion')=0
	ALTER TABLE CAJ_MovimientosCaja ADD cUsuarioAutoriza_Cancelacion varchar(100)
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','nIDCorteCaja')=0
	ALTER TABLE CAJ_MovimientosCaja ADD nIDCorteCaja bigint
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_MovimientosCaja_CAJ_CortesCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_MovimientosCaja] ADD CONSTRAINT [FK_CAJ_MovimientosCaja_CAJ_CortesCaja]
	FOREIGN KEY ([nIDCorteCaja]) REFERENCES [CAJ_CortesCaja] ([nIDCorteCaja]) ON DELETE No Action ON UPDATE No Action
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','nImporte_Respaldo')=0
	ALTER TABLE CAJ_MovimientosCaja ADD nImporte_Respaldo numeric(18,2)
GO

IF dbo.ValidaCampoTabla_Fn('CAJ_MovimientosCaja','bRegistroEspecial')=0
	ALTER TABLE CAJ_MovimientosCaja ADD bRegistroEspecial bit CONSTRAINT DF_TipoEspMC DEFAULT 0
GO

IF dbo.fn_ExisteCampo('CAJ_MovimientosCaja','bCancelado')=0
	ALTER TABLE CAJ_MovimientosCaja ADD bCancelado bit
GO