/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 16-nov.-2023 11:27:47 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAJ_DetalleDenominacionMovimientosCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAJ_DetalleDenominacionMovimientosCaja]
(
	[nIDRegistroCaja] bigint NOT NULL,    -- id
	[nRenglon] int NOT NULL,    -- consecutivo relacionado al registro de movimiento de caja indicado
	[nDenominacion] int NOT NULL,    -- id de catálogo de denominación relacionado al registro
	[nValor] decimal(18,4) NOT NULL,    -- valor de la denominación especificada
	[nCantidad] int NOT NULL,    -- cantidad de los registros capturados del folio de denominación especificado
	[nImporte] decimal(18,4) NOT NULL,    -- importe relacionado de la cantidad con el valor de la denominación
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
	/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [CAJ_DetalleDenominacionMovimientosCaja] ADD CONSTRAINT [PK_CAJ_DetalleDenominacionMovimientosCaja]
	PRIMARY KEY CLUSTERED ([nIDRegistroCaja] ASC,[nRenglon] ASC,[nDenominacion] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_DetalleDenominacionMovimientosCaja_CAT_Denominaciones' AND xtype = 'F')
	ALTER TABLE [CAJ_DetalleDenominacionMovimientosCaja] ADD CONSTRAINT [FK_CAJ_DetalleDenominacionMovimientosCaja_CAT_Denominaciones]
	FOREIGN KEY ([nDenominacion]) REFERENCES [CAT_Denominaciones] ([nDenominacion]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_DetalleDenominacionMovimientosCaja_CAJ_MovimientosCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_DetalleDenominacionMovimientosCaja] ADD CONSTRAINT [FK_CAJ_DetalleDenominacionMovimientosCaja_CAJ_MovimientosCaja]
	FOREIGN KEY ([nIDRegistroCaja]) REFERENCES [CAJ_MovimientosCaja] ([nIDRegistroCaja]) ON DELETE No Action ON UPDATE No Action
GO