/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-mar.-2024 11:01:11 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAJ_CortesCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAJ_CortesCaja]
(
	[nIDCorteCaja] bigint NOT NULL,    -- id
	[nSucursal] int NOT NULL,    -- id de la sucursal que hace el corte
	[nIDApertura] bigint NOT NULL,    -- id de apertura al que pertence el registro
	[dFechaCorte] datetime NOT NULL,    -- fecha del corte de caja
	[nDotacionInicial] decimal(18,4) NOT NULL, -- importe de dotacion inicial de la apertura
	[nTotalRetiros] decimal(18,4) NOT NULL,    -- importe total de retiros incluidos en el corte
	[nTotalGastos] decimal(18,4) NOT NULL,    -- importe total de gastos incluidos en el corte
	[nTotalIngresos] decimal(18,4) NOT NULL,    -- importe total de ingresos extras incluidos en el corte   ejemplo dotaciones de caja
	[nIDCorteGeneral] bigint NULL,    -- id de relación que indicará cuando se realice el proceso de corte general o cierre de día
	[bImpreso] bit NOT NULL,    -- campo que indica si fue impreso o no el registro
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAJ_CortesCaja] ADD CONSTRAINT [PK_CAJ_CorteCaja]
	PRIMARY KEY CLUSTERED ([nIDCorteCaja] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_CorteCaja_CAT_Sucursales' AND xtype = 'F')
	ALTER TABLE [CAJ_CortesCaja] ADD CONSTRAINT [FK_CAJ_CorteCaja_CAT_Sucursales]
	FOREIGN KEY ([nSucursal]) REFERENCES [dbo].[CAT_Sucursales] ([nSucursal]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_CortesCaja_CAJ_CortesGenerales' AND xtype = 'F')
	ALTER TABLE [CAJ_CortesCaja] ADD CONSTRAINT [FK_CAJ_CortesCaja_CAJ_CortesGenerales]
	FOREIGN KEY ([nIDCorteGeneral]) REFERENCES [CAJ_CortesGenerales] ([nIDCorteGeneral]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_CortesCaja_CAJ_RegistrosAperturaCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_CortesCaja] ADD CONSTRAINT [FK_CAJ_CortesCaja_CAJ_RegistrosAperturaCaja]
	FOREIGN KEY ([nIDApertura]) REFERENCES [CAJ_RegistrosAperturaCaja] ([nIDApertura]) ON DELETE No Action ON UPDATE No Action
GO

IF dbo.fn_ExisteCampo('CAJ_CortesCaja','nTotalIngresos_Respaldo')=0
	ALTER TABLE CAJ_CortesCaja ADD nTotalIngresos_Respaldo decimal(18,2)
GO