/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-mar.-2024 11:01:12 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAJ_DetalleCorteCaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAJ_DetalleCorteCaja]
(
	[nIDCorteCaja] bigint NOT NULL,    -- id
	[nRenglon] smallint NOT NULL,    -- id de renglon para identificar al registro, es parte de la llave
	[nFormaPago] int NOT NULL,    -- id de catálogo de la forma de pago incluida en el detalle
	[nImporteCorte] decimal(18,4) NOT NULL,    -- importe de corte obtenido por sistema de la forma de pago indicada
	[nImporteUsuario] decimal(18,4) NULL,    -- importe de corte indicado por usuario de la forma de pago indicada
	[nDiferencia] decimal(18,4) NOT NULL,    -- importe diferencia de importe corte vs importe de usuario de la forma de pago indicada para el corte
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)


/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAJ_DetalleCorteCaja] ADD CONSTRAINT [PK_CAJ_DetalleCorteCaja]
	PRIMARY KEY CLUSTERED ([nIDCorteCaja] ASC,[nRenglon] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_DetalleCorteCaja_CAJ_CorteCaja' AND xtype = 'F')
	ALTER TABLE [CAJ_DetalleCorteCaja] ADD CONSTRAINT [FK_CAJ_DetalleCorteCaja_CAJ_CorteCaja]
	FOREIGN KEY ([nIDCorteCaja]) REFERENCES [CAJ_CortesCaja] ([nIDCorteCaja]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAJ_DetalleCorteCaja_CAT_FormasPago' AND xtype = 'F')
ALTER TABLE [CAJ_DetalleCorteCaja] ADD CONSTRAINT [FK_CAJ_DetalleCorteCaja_CAT_FormasPago]
	FOREIGN KEY ([nFormaPago]) REFERENCES [CAT_FormasPago] ([nFormaPago]) ON DELETE No Action ON UPDATE No Action
GO

IF dbo.fn_ExisteCampo('CAJ_DetalleCorteCaja','nImporteCorte_Respaldo')=0
	ALTER TABLE CAJ_DetalleCorteCaja ADD nImporteCorte_Respaldo decimal(18,4)
GO

IF dbo.fn_ExisteCampo('CAJ_DetalleCorteCaja','nImporteUsuario_Respaldo')=0
	ALTER TABLE CAJ_DetalleCorteCaja ADD nImporteUsuario_Respaldo decimal(18,4)
GO

IF dbo.fn_ExisteCampo('CAJ_DetalleCorteCaja','nDiferencia_Respaldo')=0
	ALTER TABLE CAJ_DetalleCorteCaja ADD nDiferencia_Respaldo decimal(18,4)
GO
