/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 17-sep.-2023 09:25:33 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_ContactosProveedores]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_ContactosProveedores]
(
	[nProveedor] int NOT NULL,    -- id de proveedor
	[nContactoProveedor] smallint NOT NULL,    -- consecutivo de contacto del proveedor
	[cContacto] varchar(200) NOT NULL,    -- nombre del contacto del proveedor
	[cPuesto] varchar(50) NULL,    -- nombre del puesto que tiene el contacto
	[cTelefono] varchar(50) NULL,    -- número de teléfono de contacto 
	[cTelefonoAux] varchar(50) NULL,    -- número de teléfono secundario del contacto
	[cCorreo] varchar(100) NULL,    -- correo electrónico del contacto del proveedor
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_ContactosProveedores] ADD CONSTRAINT [PK_CAT_ContactosProveedores]
	PRIMARY KEY CLUSTERED ([nContactoProveedor] ASC,[nProveedor] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_ContactosProveedores_CAT_Proveedores' AND xtype = 'F')
	ALTER TABLE [CAT_ContactosProveedores] ADD CONSTRAINT [FK_CAT_ContactosProveedores_CAT_Proveedores]
	FOREIGN KEY ([nProveedor]) REFERENCES [CAT_Proveedores] ([nProveedor]) ON DELETE No Action ON UPDATE No Action
GO