/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 17-sep.-2023 09:25:34 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_ProntosPagosProveedores]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_ProntosPagosProveedores]
(
	[nProntoPago] int NOT NULL,    -- id
	[nProveedor] int NOT NULL,    -- id de catálogo al que pertenece el registro
	[nDias] smallint NOT NULL,    -- cantidad de dias en los que se debe realizar el pago para poder obtener el pronto pago
	[cDescuento] varchar(20) NOT NULL,    -- descuento asignado al pronto pago, es cadena para en caso que sea en cascada  ejemplo  5 3+2
	[nTipoAplicacion] tinyint NOT NULL,    -- indicador del tipo de registro al que aplica el pronto pago{  1=Compra 2=Gasto 0=Ambos
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [CAT_ProntosPagosProveedores] ADD CONSTRAINT [PK_CAT_ProntosPagosProveedores]
	PRIMARY KEY CLUSTERED ([nProntoPago] ASC)
END
GO

/* Create Foreign Key Constraints */

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_ProntosPagosProveedores_CAT_Proveedores' AND xtype = 'F')
	ALTER TABLE [CAT_ProntosPagosProveedores] ADD CONSTRAINT [FK_CAT_ProntosPagosProveedores_CAT_Proveedores]
	FOREIGN KEY ([nProveedor]) REFERENCES [CAT_Proveedores] ([nProveedor]) ON DELETE No Action ON UPDATE No Action
GO