/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 20-mar.-2025 10:30:20 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[IVT_SolicitudesPedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [IVT_SolicitudesPedido]
(
	[nFolioSolicitud] bigint NOT NULL,    -- id
	[nTipoSolicitud] tinyint NOT NULL,    -- campo para en caso que sea necesario separar las solicitudes por un tipo  Valores  1=Traspaso
	[nAlmacen] int NOT NULL,    -- id de catálogo de almacén que hace la solicitud de pedido
	[nAlmacenRelacionado] int NOT NULL,    -- id de catálogo de almacén que atenderá la solicitud de pedido
	[dFechaSolicitud] datetime NOT NULL,    -- fecha de la solicitud
	[nFechaSolicitud] int NULL,    -- valor de la fecha de solicitud en formato numérico
	[nEstatus] tinyint NOT NULL,    -- estatus por los que puede pasar la solicut de  pedido, sus valores estan en cat_catalogs "IVT_EstatusSolicitudPedido"
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [IVT_SolicitudesPedido] ADD CONSTRAINT [PK_IVT_SolicitudesPedido]
	PRIMARY KEY CLUSTERED ([nFolioSolicitud] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_SolicitudesPedido_CAT_Almacenes' AND xtype = 'F')
	ALTER TABLE [IVT_SolicitudesPedido] ADD CONSTRAINT [FK_IVT_SolicitudesPedido_CAT_Almacenes]
	FOREIGN KEY ([nAlmacen]) REFERENCES [dbo].[CAT_Almacenes] ([nAlmacen]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_SolicitudesPedido_CAT_Almacenes_Rel' AND xtype = 'F')
	ALTER TABLE [IVT_SolicitudesPedido] ADD CONSTRAINT [FK_IVT_SolicitudesPedido_CAT_Almacenes_Rel]
	FOREIGN KEY ([nAlmacenRelacionado]) REFERENCES [dbo].[CAT_Almacenes] ([nAlmacen]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_MovimientosInventario_IVT_SolicitudesPedido' AND xtype = 'F')
	ALTER TABLE [IVT_MovimientosInventario] ADD CONSTRAINT [FK_IVT_MovimientosInventario_IVT_SolicitudesPedido]
	FOREIGN KEY ([nFolioSolicitud]) REFERENCES [dbo].[IVT_SolicitudesPedido] ([nFolioSolicitud]) ON DELETE No Action ON UPDATE No Action
GO