/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 20-mar.-2025 10:30:21 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[IVT_SolicitudesPedidoDetalle]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [IVT_SolicitudesPedidoDetalle]
(
	[nFolioSolicitud] bigint NOT NULL,    -- id de la solicitud de pedido al que se relaciona el registro
	[nRenglon] smallint NOT NULL,    -- consecutivo de renglón de número de registro 
	[nTipoSolicitud] tinyint NOT NULL,
	[nAlmacen] int NOT NULL,    -- id de catálogo de almacén que realiza la solicitud de pedido
	[nFechaSolicitud] int NOT NULL,    -- fecha de la solicitud en formato numérico
	[nIDArticulo] int NOT NULL,    -- id de catálogo de artículo del registro al que se le hace pedido
	[nCantidad] decimal(18,4) NOT NULL,    -- cantidad solicitada
	[nCantidadSurtida] decimal(18,4) NOT NULL,    -- cantidad del artículo que se ha surtido respecto a lo solicitado, esta cantidad se ira actualizando con los procesos de aplicación de movimientos de sxt o sus respectivas cancelaciones
	[nCantidadRecibida] decimal(18,4) NOT NULL,    -- cantidad del artículo que se ha recibido respecto a lo surtido, esta cantidad se ira actualizando con los procesos de aplicación de movimientos de ext o sus respectivas cancelaciones
	[nCosto] decimal(18,4) NULL,    -- opcional, valor del último costo del artículo al momento de hacer el registro
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)

/* Create Primary Keys, Indexes, Uniques, Checks */
	ALTER TABLE [IVT_SolicitudesPedidoDetalle] ADD CONSTRAINT [PK_IVT_SolicitudesPedidoDetalle]
	PRIMARY KEY CLUSTERED ([nFolioSolicitud] ASC,[nRenglon] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_SolicitudesPedidoDetalle_CAT_Almacenes' AND xtype = 'F')
	ALTER TABLE [IVT_SolicitudesPedidoDetalle] ADD CONSTRAINT [FK_IVT_SolicitudesPedidoDetalle_CAT_Almacenes]
	FOREIGN KEY ([nAlmacen]) REFERENCES [dbo].[CAT_Almacenes] ([nAlmacen]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_SolicitudesPedidoDetalle_CAT_Articulos' AND xtype = 'F')
	ALTER TABLE [IVT_SolicitudesPedidoDetalle] ADD CONSTRAINT [FK_IVT_SolicitudesPedidoDetalle_CAT_Articulos]
	FOREIGN KEY ([nIDArticulo]) REFERENCES [CAT_Articulos] ([nIDArticulo]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_SolicitudesPedidoDetalle_IVT_SolicitudesPedido' AND xtype = 'F')
	ALTER TABLE [IVT_SolicitudesPedidoDetalle] ADD CONSTRAINT [FK_IVT_SolicitudesPedidoDetalle_IVT_SolicitudesPedido]
	FOREIGN KEY ([nFolioSolicitud]) REFERENCES [IVT_SolicitudesPedido] ([nFolioSolicitud]) ON DELETE No Action ON UPDATE No Action
GO

IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_IVT_MovimientosInventarioDetalle_IVT_SolicitudesPedidoDetalle' AND xtype = 'F')
	ALTER TABLE [IVT_MovimientosInventarioDetalle] ADD CONSTRAINT [FK_IVT_MovimientosInventarioDetalle_IVT_SolicitudesPedidoDetalle]
	FOREIGN KEY ([nFolioSolicitud],[nRenglonSolicitud]) REFERENCES [IVT_SolicitudesPedidoDetalle] ([nFolioSolicitud],[nRenglon]) ON DELETE No Action ON UPDATE No Action
GO