/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 05-feb.-2025 10:36:05 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_GrupoEmpresarial]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[CAT_GrupoEmpresarial]
(
	[nGrupoEmpresarial] int NOT NULL,
	[cDescripcion] varchar(200) NOT NULL,
	[bActivo] bit NOT NULL DEFAULT 1,
	[cUsuario_Registra] varchar(50) NULL,
	[cMaquina_Registra] varchar(50) NULL,
	[dFecha_Registra] smalldatetime NULL,
	[cUsuario_Modifica] varchar(50) NULL,
	[cMaquina_Modifica] varchar(50) NULL,
	[dFecha_Modifica] varchar(50) NULL,
	[cUsuario_Cancela] varchar(50) NULL,
	[cMaquina_Cancela] varchar(50) NULL,
	[dFecha_Cancela] smalldatetime NULL
)


	/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [dbo].[CAT_GrupoEmpresarial] ADD CONSTRAINT [PK_CAT_GrupoEmpresarial]
	PRIMARY KEY CLUSTERED ([nGrupoEmpresarial] ASC)
END
GO