/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 17-sep.-2023 09:25:34 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */
IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CAT_Proveedores]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [CAT_Proveedores]
(
	[nProveedor] int NOT NULL,    -- id
	[cDescripcionComercial] varchar(200) NOT NULL,    -- nombre comercial del proveedor
	[cDescripcionFiscal] varchar(200) NULL,    -- nombre fiscal del proveedor
	[cColonia] varchar(50) NOT NULL,    -- id de catálogo de la colonia del domicilio del empleado
	[cCodigoPostal] varchar(50) NOT NULL,    -- código postal de la dirección del proveedor
	[cRFC] varchar(20) NULL,    -- rfc del proveedor
	[cCURP] varchar(50) NULL,    -- dato de CURP del proveedor en caso de aplicar
	[nTipoPersona] tinyint NULL,    -- tipo de clasificacion del proveedor ante el sat  1=Fisica 2=Moral
	[bNacional] bit NOT NULL,    -- campo para saber si el proveedor es nacional
	[nDiasCredito] tinyint NOT NULL,    -- cantidad de días de crédito que se puede negociar con el proveedor
	[cTelefono] varchar(20) NULL,    -- número telefónico del proveedor
	[cCorreo] varchar(100) NULL,    -- correo electrónico del proveedor
	[bActivo] bit NOT NULL,    -- campo que indica si está activo o no el registro
	[cUsuario_Registra] varchar(50) NOT NULL,    -- login del usuario que realiza el registro
	[cMaquina_Registra] varchar(50) NOT NULL,    -- nombre del equipo desde donde se realiza el registro
	[dFecha_Registra] datetime NOT NULL,    -- fecha en que se hace el registro
	[cUsuario_Modifica] varchar(50) NULL,    -- login del usuario que realiza la ultima modificación del registro
	[cMaquina_Modifica] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima modificación del registro
	[dFecha_Modifica] datetime NULL,    -- fecha en que se hace la ultima modificación del registro
	[cUsuario_Cancela] varchar(50) NULL,    -- login del usuario que realiza la ultima inactivación del registro
	[cMaquina_Cancela] varchar(50) NULL,    -- nombre del equipo desde donde se realiza la ultima inactivación del registro
	[dFecha_Cancela] datetime NULL    -- fecha en que se hace la ultima inactivación del registro
)
/* Create Primary Keys, Indexes, Uniques, Checks */

	ALTER TABLE [CAT_Proveedores] ADD CONSTRAINT [PK_CAT_Proveedores]
	PRIMARY KEY CLUSTERED ([nProveedor] ASC)
END
GO

/* Create Foreign Key Constraints */
IF not EXISTS (SELECT 1 FROM SysObjects (NOLOCK) where name ='FK_CAT_Proveedores_CAT_Colonias' AND xtype = 'F')
	ALTER TABLE [CAT_Proveedores] ADD CONSTRAINT [FK_CAT_Proveedores_CAT_Colonias]
	FOREIGN KEY ([cColonia],[cCodigoPostal]) REFERENCES [dbo].[CAT_Colonias] ([cColonia],[cCodigoPostal]) ON DELETE No Action ON UPDATE No Action
GO